language: php
dist: trusty
sudo: false

matrix:
  include:
    - php: "7.2"
      env:
        - LARAVEL_VERSION=^7.0
        - PHPUNIT_VERSION=^8.0
    - php: "7.3"
      env:
        - LARAVEL_VERSION=^7.0
        - PHPUNIT_VERSION=^9.0
    - php: "7.4"
      env:
        - LARAVEL_VERSION=^7.0
        - PHPUNIT_VERSION=^9.0

install:
  - composer require "laravel/framework:${LARAVEL_VERSION}" --no-update -n
  - composer require "phpunit/phpunit:${PHPUNIT_VERSION}" --dev --no-update -n
  - travis_retry composer install --no-suggest --prefer-dist -n -o

script:
  - vendor/bin/phpunit
